# Generated by Django 2.0.5 on 2018-05-24 20:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("publications", "0002_auto_20170602_1055")]

    operations = [
        migrations.AlterField(
            model_name="publication",
            name="Owner",
            field=models.ForeignKey(
                help_text='Only people with the "publications" flag are shown',
                limit_choices_to={"active": True, "flags__slug": "publications"},
                on_delete=django.db.models.deletion.CASCADE,
                to="people.Person",
            ),
        ),
        migrations.AlterField(
            model_name="publication",
            name="URL",
            field=models.URLField(
                blank=True,
                help_text="(Optional) A link to an online version or further information",
                null=True,
                verbose_name="URL",
            ),
        ),
        migrations.AlterField(
            model_name="publication",
            name="volume",
            field=models.CharField(
                blank=True,
                help_text="The volume of a journal or multi-volume book",
                max_length=32,
                null=True,
            ),
        ),
    ]
