# Generated by Django 2.0.5 on 2018-05-25 15:22

from django.db import migrations, models


def fill_mymodel_id(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    MyModel = apps.get_model("publications", "Publication")
    for n, obj in enumerate(MyModel.objects.using(db_alias).all()):
        obj.id = n
        obj.save()


class Migration(migrations.Migration):

    dependencies = [("publications", "0003_auto_20180524_1542")]

    operations = [
        migrations.AddField(
            model_name="publication",
            name="id",
            # field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            field=models.IntegerField(null=True),
        ),
        migrations.RunPython(fill_mymodel_id, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="publication", name="Reference_Key", field=models.SlugField()
        ),
        migrations.AlterField(
            model_name="publication",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
