# Generated by Django 2.0.5 on 2018-05-25 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("publications", "0004_auto_20180525_1022")]

    operations = [
        migrations.AlterField(
            model_name="publication",
            name="author",
            field=models.CharField(
                blank=True,
                help_text="The name(s) of the author(s) (in the case of more than one author, separated by &quot;and&quot;, very long lists can be truncated with &quot;and others&quot;), in the format &quot;Familyname, G.&quot; or &quot;Familyname, Given&quot;",
                max_length=512,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="publication",
            name="year",
            field=models.CharField(
                blank=True,
                help_text="The year of publication (or, if unpublished, the year of creation)",
                max_length=32,
                null=True,
            ),
        ),
    ]
