# Generated by Django 2.0.5 on 2018-05-28 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("publications", "0005_auto_20180525_1527")]

    operations = [
        migrations.AlterField(
            model_name="publication",
            name="chapter",
            field=models.CharField(
                blank=True, help_text="The chapter number", max_length=64, null=True
            ),
        )
    ]
