# Generated by Django 2.0.5 on 2018-05-29 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("publications", "0006_auto_20180528_1118")]

    operations = [
        migrations.AlterField(
            model_name="publication",
            name="chapter",
            field=models.CharField(
                blank=True, help_text="The chapter number", max_length=128, null=True
            ),
        ),
        migrations.AlterField(
            model_name="publication",
            name="edition",
            field=models.CharField(
                blank=True,
                help_text="The edition of a book, long form (such as &quot;first&quot; or &quot;second&quot;)",
                max_length=128,
                null=True,
            ),
        ),
    ]
