# Generated by Django 2.1.5 on 2019-02-05 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("publications", "0007_auto_20180529_0803")]

    operations = [
        migrations.AlterField(
            model_name="publication",
            name="URL",
            field=models.URLField(
                blank=True,
                help_text="(Optional) A link to an online version or further information",
                max_length=512,
                null=True,
                verbose_name="URL",
            ),
        )
    ]
